AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LIMS-dev

  Sample SAM Template for LIMS-dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  LimsDevFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lims-dev/
      Handler: app.app
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        LimsDev:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LimsDevApi:
    Description: "API Gateway endpoint URL for Prod stage for LimsDev function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LimsDevFunction:
    Description: "  LimsDev Lambda Function ARN"
    Value: !GetAtt LimsDevFunction.Arn
  LimsDevIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LimsDevFunctionRole.Arn
